multipass: true

plugins:
  - addAttributesToSVGElement: false
  - addClassesToSVGElement: false
  - cleanupAttrs: true
  - cleanupEnableBackground: true
  - cleanupIDs: true
  - cleanupListOfValues: true
  - cleanupNumericValues: true
  - collapseGroups: true
  - convertColors: true
  - convertPathData: true
  - convertShapeToPath: true
  - convertStyleToAttrs: true
  - convertTransform: true
  - mergePaths: true
  - minifyStyles: true
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - removeAttrs: false
  - removeComments: true
  - removeDesc: true
  - removeDimensions: false
  - removeDoctype: true
  - removeEditorsNSData: true
  - removeElementsByAttr: false
  - removeEmptyAttrs: true
  - removeEmptyContainers: true
  - removeEmptyText: true
  - removeHiddenElems: true
  - removeMetadata: true
  - removeNonInheritableGroupAttrs: true
  - removeRasterImages: true
  - removeStyleElement: true
  - removeTitle: true
  - removeUnknownsAndDefaults:
      keepDataAttrs: false
  - removeUnusedNS: true
  - removeUselessDefs: true
  - removeUselessStrokeAndFill: true
  - removeViewBox: true
  - removeXMLNS: false
  - removeXMLProcInst: true
  - sortAttrs: true

js2svg:
  pretty: true
  indent: '  '